FROM eclipse-temurin:21-jre
WORKDIR /app
COPY build/libs/cookbook.jar app.jar
EXPOSE 8080
EXPOSE 5005
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "app.jar"]