FROM eclipse-temurin:25-jre
WORKDIR /app
COPY extractor/build/libs/cookbook.jar app.jar
EXPOSE 8080
EXPOSE 5005
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "app.jar"]